#!/system/bin/sh
UNINSTALL="pm uninstall -k --user 0"

${UNINSTALL} com.google.android.calendar  
${UNINSTALL} com.google.android.apps.docs 
${UNINSTALL} com.google.android.apps.tachyon 
${UNINSTALL} com.android.facelock 
${UNINSTALL} com.android.htmlviewer 
${UNINSTALL} com.android.keychain 
${UNINSTALL} com.google.android.apps.maps 
${UNINSTALL} com.google.android.music  
${UNINSTALL} com.google.android.apps.photos 
${UNINSTALL} com.oppo.market
${UNINSTALL} com.oppo.sos
${UNINSTALL} com.nearme.browser
${UNINSTALL} com.coloros.calculator
${UNINSTALL} com.coloros.compass2
${UNINSTALL} com.oppo.music
${UNINSTALL} com.coloros.soundrecorder
${UNINSTALL} com.redteamobile.roaming
${UNINSTALL} com.coloros.assistantscreen2
${UNINSTALL} com.coloros.video
${UNINSTALL} com.google.android.marvin.talkback
${UNINSTALL} com.facebook.appmanager
${UNINSTALL} com.facebook.services
${UNINSTALL} com.facebook.system
${UNINSTALL} com.heytap.market
${UNINSTALL} com.heytap.market
${UNINSTALL} com.google.android.videos
${UNINSTALL} com.google.android.apps.photos
${UNINSTALL} com.google.android.keep
${UNINSTALL} com.heytap.cloud
${UNINSTALL} com.google.android.youtube
${UNINSTALL} com.google.android.apps.youtube.music
${UNINSTALL}  com.coloros.backuprestore
${UNINSTALL}  com.coloros.phonenoareainquire
${UNINSTALL}  com.coloros.healthcheck
${UNINSTALL}  com.coloros.assistantscreen2
${UNINSTALL}  com.coloros.activation
${UNINSTALL}  com.coloros.feedback
${UNINSTALL}  com.coloros.securepay
${UNINSTALL}  com.coloros.sauhelper
${UNINSTALL}  com.coloros.findmyphone
${UNINSTALL}  com.realme.findphone.client2
${UNINSTALL}  com.coloros.childrenspace
${UNINSTALL}  com.coloros.floatassistant
${UNINSTALL}  com.oppo.oppopowermonitor
${UNINSTALL}  com.oppo.logkit
${UNINSTALL}  com.oppo.atlas
${UNINSTALL}  com.oppo.music
${UNINSTALL}  com.oppo.criticallog
${UNINSTALL}  com.oppo.lfeh
${UNINSTALL}  com.heytap.cloud
${UNINSTALL}  com.heytap.habit.analysis
${UNINSTALL}  com.heytap.market
${UNINSTALL}  com.coloros.backuprestore.remoteservice
${UNINSTALL}  com.coloros.smartdrive
${UNINSTALL}  com.coloros.ocrscanner
${UNINSTALL}  com.coloros.directui
${UNINSTALL}  com.heytap.speechassist
${UNINSTALL}  com.heytap.browser
${UNINSTALL}  com.coloros.sceneservice
${UNINSTALL}  com.ted.number
${UNINSTALL}  com.heytap.openid
${UNINSTALL}  com.coloros.remoteguardservice
${UNINSTALL}  com.heytap.quicksearchbox
${UNINSTALL}  com.sohu.inputmethod.sogouoem
${UNINSTALL}  com.heytap.themestore
${UNINSTALL}  com.coloros.translate.engine
${UNINSTALL}  com.coloros.operationManual
${UNINSTALL}  com.heytap.speechassist.engine
${UNINSTALL}  com.finshell.wallet
${UNINSTALL}  com.coloros.wifibackuprestore
${UNINSTALL}  com.coloros.oshare
${UNINSTALL}  com.iflytek.speechsuite
${UNINSTALL}  com.android.chrome
${UNINSTALL}  com.finshell.fin
${UNINSTALL} com.google.android.calendar  
${UNINSTALL} com.google.android.apps.docs 
${UNINSTALL} com.google.android.apps.tachyon 
${UNINSTALL} com.android.facelock 
${UNINSTALL} com.android.htmlviewer 
${UNINSTALL} com.android.keychain 
${UNINSTALL} com.google.android.apps.maps 
${UNINSTALL} com.google.android.music  
${UNINSTALL} com.google.android.apps.photos 
${UNINSTALL} com.oppo.market
${UNINSTALL} com.nearme.browser
${UNINSTALL} com.coloros.calculator
${UNINSTALL} com.coloros.compass2
${UNINSTALL} com.oppo.music
${UNINSTALL} com.coloros.soundrecorder
${UNINSTALL} com.redteamobile.roaming
${UNINSTALL} com.coloros.assistantscreen2
${UNINSTALL} com.coloros.video
${UNINSTALL} com.coloros.weather2.service
${UNINSTALL} com.coloros.weather2
${UNINSTALL} com.google.android.marvin.talkback
${UNINSTALL} com.facebook.appmanager
${UNINSTALL} com.facebook.services
${UNINSTALL} com.facebook.system
${UNINSTALL} com.heytap.market
${UNINSTALL} com.heytap.market
${UNINSTALL} com.google.android.videos
${UNINSTALL} com.google.android.apps.photos
${UNINSTALL} com.google.android.keep
${UNINSTALL} com.heytap.cloud
${UNINSTALL} com.google.android.youtube
${UNINSTALL} com.google.android.apps.youtube.music
${UNINSTALL} com.coloros.backuprestore
${UNINSTALL} com.coloros.phonenoareainquire
${UNINSTALL} com.coloros.healthcheck
${UNINSTALL} com.coloros.assistantscreen2
${UNINSTALL} com.coloros.activation
${UNINSTALL} com.coloros.feedback
${UNINSTALL} com.coloros.securepay
${UNINSTALL} com.coloros.sauhelper
${UNINSTALL} com.coloros.findmyphone
${UNINSTALL} com.realme.findphone.client2
${UNINSTALL} com.coloros.childrenspace
${UNINSTALL} com.coloros.floatassistant
${UNINSTALL} com.oppo.oppopowermonitor
${UNINSTALL} com.oppo.ota1
${UNINSTALL} com.oppo.logkit
${UNINSTALL} com.oppo.atlas
${UNINSTALL} com.oppo.music
${UNINSTALL} com.oppo.otaui2
${UNINSTALL} com.oppo.criticallog
${UNINSTALL} com.oppo.lfeh
${UNINSTALL} com.heytap.cloud
${UNINSTALL} com.heytap.habit.analysis
${UNINSTALL} com.heytap.market
${UNINSTALL} com.heytap.usercenterjg
${UNINSTALL} com.coloros.backuprestore.remoteservice
${UNINSTALL} com.coloros.smartdrive
${UNINSTALL} com.coloros.ocrscanner
${UNINSTALL} com.coloros.directui
${UNINSTALL} com.heytap.speechassist
${UNINSTALL} com.heytap.browser
${UNINSTALL} com.coloros.sceneservice
${UNINSTALL} com.ted.number
${UNINSTALL} com.heytap.openid
${UNINSTALL} com.coloros.remoteguardservice
${UNINSTALL} com.heytap.quicksearchbox
${UNINSTALL} com.sohu.inputmethod.sogouoem
${UNINSTALL} com.heytap.themestore
${UNINSTALL} com.coloros.translate.engine
${UNINSTALL} com.coloros.operationManual
${UNINSTALL} com.heytap.speechassist.engine
${UNINSTALL} com.finshell.wallet
${UNINSTALL} com.coloros.wifibackuprestore
${UNINSTALL} com.coloros.oshare
${UNINSTALL} com.iflytek.speechsuite
${UNINSTALL} com.android.chrome